apiVersion: v1
kind: ConfigMap
metadata:
  name: my-db-connector-config
  namespace: debezium
data:
  database.server.name: my-db-server
  database.hostname: my-db-host
  database.port: "5432"
  database.user: my-db-username
  database.password: my-db-password
  database.dbname: my-database
  database.whitelist: my-database